"""Constants used in the Symbolic expressions."""

import symbolic_expr_priors


SYMBOLIC_EXPR_PRIORS_TWO_VARIABLE = (
    {
        "sim": "math",
        "variable_count": 2,
        "variables": ("theta", "theta1"),
        "theta": (-10, 10),
        "theta1": (-10, 10),
        "function": symbolic_expr_priors.gaussian_prob_density_2d,
        "classes": ("ex", "py", "mu"),
    },
    {
        "sim": "relative",
        "variable_count": 2,
        "variables": ("mass", "velocity"),
        "mass": (100.0, 10_000.0),
        "velocity": (500.0, 100_000.0),
        "function": symbolic_expr_priors.relative_mass,
        "classes": ("dv", "sq", "py"),
    },
)

SYMBOLIC_EXPR_PRIORS_ONE_VARIABLE = (
    {
        "sim": "math",
        "variable_count": 1,
        "variables": ("x"),
        "x": (-10, 10),
        "function": symbolic_expr_priors.gaussian_prob_density,
        "classes": ("py", "ex"),
        "hint": "guassian",
    },
    {
        "sim": "math",
        "variable_count": 1,
        "variables": ("x"),
        "x": (-10, 10),
        "function": symbolic_expr_priors.nguyen1_poly_expression1,
        "classes": ("ad", "py"),
        "hint": "polynomial",
    },
    {
        "sim": "math",
        "variable_count": 1,
        "variables": ("x"),
        "x": (-10, 10),
        "function": symbolic_expr_priors.nguyen1_poly_expression2,
        "classes": ("ad", "py"),
        "hint": "polynomial",
    },
    {
        "sim": "math",
        "variable_count": 1,
        "variables": ("x"),
        "x": (-3.14, 3.14),
        "function": symbolic_expr_priors.nguyen1_poly_trig_expression1,
        "classes": ("si", "py", "mu", "co"),
        "hint": "Trigonomtric and polynomial",
    },
    {
        "sim": "math",
        "variable_count": 1,
        "variables": ("x"),
        "x": (-3.14, 3.14),
        "function": symbolic_expr_priors.nguyen1_poly_trig_expression2,
        "classes": ("ad", "si", "ad", "ex"),
        "hint": "Trigonomtric and polynomial",
    },
    {
        "sim": "math",
        "variable_count": 1,
        "variables": ("x"),
        "x": (0.1, 100),
        "function": symbolic_expr_priors.nguyen1_log_expression1,
        "classes": ("ad", "ln", "py"),
        "hint": "Logorithmic"
    },
    {
        "sim": "math",
        "variable_count": 1,
        "variables": ("x"),
        "x": (-1.0, 1.0),
        "function": symbolic_expr_priors.sthoppay_math_expression1,
        "classes": ("ad", "co", "si", "py"),
        "hint": "Trigonomtric and polynomial",
    },
    {
        "sim": "math",
        "variable_count": 1,
        "variables": ("x"),
        "x": (-1.0, 1.0),
        "function": symbolic_expr_priors.sthoppay_math_expression2,
        "classes": ("su", "ad", "ac", "py", "ta"),
        "hint": "Trigonomtric and polynomial",
    },
    {
        "sim": "math",
        "variable_count": 1,
        "variables": ("x"),
        "x": (-1.0, 1.0),
        "function": symbolic_expr_priors.sthoppay_math_expression3,
        "classes": ("mu", "dv", "as", "ta", "co"),
        "hint": "Trigonomtric and polynomial",
    },
    {
        "sim": "math",
        "variable_count": 1,
        "variables": ("x"),
        "x": (0, 2.0),
        "function": symbolic_expr_priors.sthoppay_math_expression4,
        "classes": ("ln", "ad", "py"),
        "hint": "Logorithmic and polynomial",
    },
    {
        "sim": "math",
        "variable_count": 1,
        "variables": ("x"),
        "x": (0, 2.0),
        "function": symbolic_expr_priors.sthoppay_math_expression5,
        "classes": ("dv", "ln", "at"),
        "hint": "Logorithmic and Trigonomtric",
    },
    {
        "sim": "math",
        "variable_count": 1,
        "variables": ("x"),
        "x": (0, 2.0),
        "function": symbolic_expr_priors.sthoppay_math_expression6,
        "classes": ("mu", "ln", "sq", "py"),
        "hint": "Logorithmic and polynomial",
    },
    {
        "sim": "math",
        "variable_count": 1,
        "variables": ("x"),
        "x": (-2.0, 2.0),
        "function": symbolic_expr_priors.sthoppay_math_expression7,
        "classes": ("mu", "co", "si"),
        "hint": "Trigonomtric",
    },
    {
        "sim": "math",
        "variable_count": 1,
        "variables": ("x"),
        "x": (0, 2.0),
        "function": symbolic_expr_priors.sthoppay_math_expression8,
        "classes": ("sq",),
        "hint": "polynomial",
    },
    {
        "sim": "math",
        "variable_count": 1,
        "variables": ("x"),
        "x": (0, 2.0),
        "function": symbolic_expr_priors.sthoppay_math_expression9,
        "classes": ("py", "ex", "dv"),
        "hint": "polynomial",
    },
    {
        "sim": "math",
        "variable_count": 1,
        "variables": ("x"),
        "x": (0, 2.0),
        "function": symbolic_expr_priors.sthoppay_math_expression10,
        "classes": ("ex", "py", "ad", "si"),
        "hint": "Exponential, trigonometric and polynomial",
    },
)
